name: Playwright Tests
on:
  pull_request:
    branches: [release, main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./extension
        run: npm ci
      - name: Build extension
        working-directory: ./extension
        run: npm run build
      - name: Install Playwright Browsers
        working-directory: ./extension
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./extension
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
