name: Build extensions and upload them

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    permissions: write-all
    environment: release
    runs-on: ubuntu-latest
    steps:
      