name: Build extensions and upload them

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    permissions: write-all
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.0.0
      - name: Build build folders
        run: |
          cd extensions
          chmod 777 build_dev.sh 
          chmod 777 copy_folder.sh 
          ./build_dev.sh
          cd ..
      - name: Zip Chrome
        run: zip -r chrome.zip ./extensions/chrome_dev
      # Zip Firefox
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: "chrome.zip"
          verbose: true
      
