name: Build extensions and upload them

on:
  push:
    branches:
      - release

jobs:
  publish_extension:
    permissions: write-all
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.0.0
      - name: Build build folders
        run: cd extensions
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - name: Install dependencies
        run: npm install
      - name: Compile
        run: npm run build
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: "build/chromium.zip"
          edge-file: "build/chromium.zip"
          firefox-file: "build/firefox.zip"
          verbose: true
      
